Add origin to exported ImagePlus
BIOP/bigdataviewer-biop-tools pull request #20
Opened 2021-09-21 15:19 UTC by tischi

@NicoKiaru 

For one of our projects it is important that we keep track of where we "cropped" the image in BDV that we export. I therefore added code here to add the origin (upper left corner of the BDV window) to the ImagePlus.

If you want we could make this optional by adding a boolean parameter to the Command.

I guess we should then also add the same functionality to the advanced version of the export Command. 

What do you think? (We really need it)

<img width="175" alt="image" src="https://user-images.githubusercontent.com/2157566/134198437-db0af296-70dc-4989-a7df-0f12d80d96aa.png">

<img width="200" alt="image" src="https://user-images.githubusercontent.com/2157566/134198685-64d5e795-f5ff-4b81-8b76-845b7c5f82d2.png">

2021-09-22 07:00 UTC, NicoKiaru commented
It's actually already there:
https://github.com/BIOP/bigdataviewer-biop-tools/blob/832351fd5d134ef60974c9d9d96691a97c215cca/src/main/java/bdv/util/ImagePlusHelper.java#L83

https://github.com/BIOP/bigdataviewer-biop-tools/blob/832351fd5d134ef60974c9d9d96691a97c215cca/src/main/java/bdv/util/ImagePlusHelper.java#L124

The full matrix is store in the info field of the ImagePlus

2021-09-22 07:13 UTC, tischi commented
> The full matrix is stored in the info field of the ImagePlus

Yes, but this matrix is not used by the ImagePlus viewer while the `imp.getCalibration().offset` is actually used. See above screenshot where the upper left corner is now at a negative coordinate in the ImagePlus viewer!

2021-09-22 07:25 UTC, NicoKiaru commented
Ok, it's just that this setOrigin would be better inside ImagePlus helper.

It's true that I removed the offset because I noticed an issue  when the offset is zero:

https://github.com/BIOP/bigdataviewer-biop-tools/blob/832351fd5d134ef60974c9d9d96691a97c215cca/src/main/java/bdv/util/ImagePlusHelper.java#L102-L104

With your method there are 2 incompatible ways to store the transform. I also deal with the origin but it apparently doesn't fit your use case. So we need to figure this.

2021-09-22 07:36 UTC, tischi commented
> Ok, it's just that this setOrigin would be better inside ImagePlus helper.

I totally agree!

> It's true that I removed the offset because I noticed an issue when the offset is zero:

Could you explain the issue? 
From what you said it feels like we can probably just add a `if ( offset != zero ){ change calibration offset }`?!

2021-09-23 06:08 UTC, tischi commented
@NicoKiaru 
I tried the following:
```
            imageplus.getCalibration().xOrigin = 1;
            imageplus.getCalibration().yOrigin = 1;
            imageplus.getCalibration().zOrigin = 1;
            imageplus.getCalibration().xOrigin = 0;
            imageplus.getCalibration().yOrigin = 0;
            imageplus.getCalibration().zOrigin = 0;
```
And it in fact does set it back to zero; so I don't see an issue with the zero offset case.

Would it be OK for you if I added a `pixelOffset( double[3] )` field to the `ImagePlusSampler.Builder()`?

Then one can still decide whether to use is or not, e.g. by adding a checkbox in the respective Commands.

> With your method there are 2 incompatible ways to store the transform. I also deal with the origin but it apparently doesn't fit your use case.

Could you explain this? You are storing the full affine transform in the ImagePlus info, isn't it? Does this also contain information about the voxel size (if so, then already this information would be stored twice in the image, isn't it)? And could this also contain rotations and other information that cannot be captured by the normal calibration information in the ImagePlus?

2021-09-25 17:41 UTC, NicoKiaru commented
Now I remember that the x,y,z Origin are supposed to be in pixels (https://imagej.nih.gov/ij/developer/api/ij/ij/measure/Calibration.html#xOrigin)

I guess that it's used to copy and paste a ROI from one ImagePlus to another. But if you want to store physical coordinates, then this doesn't make a lot of sense.

But ok, I saw your code and this could work in some cases. So let's try.

2021-09-25 17:48 UTC, NicoKiaru requested changes

2021-09-25 17:48 UTC, NicoKiaru commented on src/main/java/ch/epfl/biop/bdv/command/exporter/BasicBdvViewToImagePlusExportCommand.java
>                      .get();
The get method calls `ImagePlusHelper.storeExtendedCalibrationToImagePlus` this is where we need to set the origin, and not in the command

2021-09-25 18:12 UTC, NicoKiaru commented
I modified spimdata-extra, I'll cut a release, and I think this will work, no modification in this repo needed anymore.

2021-09-27 05:51 UTC, tischi commented
> Now I remember that the x,y,z Origin are supposed to be in pixels 

Yes, but when you hover with the mouse over the ImagePlus it'll show you the pixel origin multiplied with the calibration; so you'll actually see the correct physical coordinates (at least that I think I got when I tested it last week). In other words, in order for this to work as intended would actually need to store the origin in pixel units. Is that what you did in spimdata-extra (thanks a lot by the way ❤️ )?

2021-09-27 06:05 UTC, NicoKiaru commented
Yes. If you activate the abba experimental update site that will work. Fyi I switched all repos to github actions and because of some adjustements the version numbers have increased. Check on maven and let me know if there s an issue with the updates.

Regarding this issue, with the modification in spimdata extras, everything should be alright, but let me know if that s not the case.

2021-10-08 14:36 UTC, closed without merging